/*
 * Пример API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package auth_service

type RegisterBody struct {
	Username string `json:"username"`

	Password string `json:"password"`
}
