/*
 * Пример API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"jwt_handlers"
	"mongo"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	sw "auth_service/go"
)

func main() {
	log.Printf("Server starting")

	// redis.InitRedisClient()

	mongo.InitMongoClient()
	defer mongo.CloseMongoClient()

	jwt_handlers.InitJWTHandlers()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
