/*
 * Пример API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"context"
	"log"
	"net/http"

	"jwt_handlers"
	"redis"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	sw "api_handlers"
	//
	// sw "sw"
)

func main() {
	log.Printf("Server started")

	redis.InitRedisClient()
	jwt_handlers.InitJWTHandlers()

	rdb := redis.GetRedisClient()
	rdb.Set(context.Background(), "key", "value", 0)
	val, err := rdb.Get(context.Background(), "key").Result()
	if err != nil {
		log.Printf("Error: %v", err)
	} else {
		log.Printf("Value: %v", val)
	}

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
