/*
 * Пример API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	"github.com/kazalika/TaskTracker/tree/rest_api/src/auth_service/redis"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	sw "github.com/kazalika/TaskTracker/tree/rest_api/src/auth_service/go"
	//
	// sw "sw"
)

func main() {
	log.Printf("Server started")

	redis.InitRedisClient()
	redis.InitJWTHandlers()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
