version: '3.7'

services:
  auth:
    build: 
      context: ./auth_service
    volumes:
    - ./task_service:/task_service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_SERVER=mongodb://user:pass@mongodb
      - KAFKA_URL=kafka:9092

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./auth_data
        target: /auth_data/db

  task_service:
    build:
     context: ./task_service
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
      - auth
      - statistics_service
  
  postgresql:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DB=task_service_db
      - POSTGRES_USER=main_user
      - POSTGRES_PASSWORD=very_strong_generated_password
    volumes:
      - ./task_service/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: org.apache.kafka=INFO,org.apache.zookeeper=INFO
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  clickhouse:
    image: yandex/clickhouse-server
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_PORT: 9000
      # KAFKA_BROKERS: kafka:9092
      # KAFKA_TOPIC_VIEW: views
      # KAFKA_TOPIC_LIKES: likes
    volumes:
      - ./statistics_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "9000:9000"
      - "8123:8123"

  statistics_service:
    build:
     context: ./statistics_service
    ports:
      - "8090:8090"
    depends_on:
      - kafka
      - clickhouse
